// Generated by CoffeeScript 1.6.3
$(function() {
  var controller, f, fades, p, people, _i, _j;
  $(window).scroll(function() {
    return $("#counting-stars").get(0).play();
  });
  controller = $.superscrollorama();
  fades = $(".intro2-line").length;
  for (f = _i = 1; 1 <= fades ? _i <= fades : _i >= fades; f = 1 <= fades ? ++_i : --_i) {
    controller.addTween("#intro2-line" + f, TweenMax.from($("#intro2-line" + f), 1, {
      css: {
        opacity: 0
      }
    }));
  }
  people = $(".friend").length;
  for (p = _j = 1; 1 <= people ? _j <= people : _j >= people; p = 1 <= people ? ++_j : --_j) {
    controller.addTween("#friend" + p, TweenMax.to($("#friend" + p), 1, {
      css: {
        opacity: 1
      }
    }));
    controller.addTween("#word" + p, TweenMax.to($("#word" + p), 0.5, {
      css: {
        "opacity": 1
      }
    }));
  }
  return controller.addTween("#end-line1", TweenMax.from($("#end-line1"), 1, {
    css: {
      opacity: 0
    }
  }));
});
